apiVersion: skaffold/v4beta2
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false #no automate push to dockerhub
  artifacts:
    - image: mantillabigfoot/client
      context: client # references to client directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # if changes made to a .js file copy to pod...otherwise rebuild entire image
            dest: . # copy to pod
    - image: mantillabigfoot/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mantillabigfoot/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mantillabigfoot/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mantillabigfoot/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: mantillabigfoot/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
