apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template: #tell Depl which pods to manage
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mantillabigfoot/client
          imagePullPolicy: Never
--- # create new Object
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP # default
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000 #port of the k8s service
      targetPort: 3000  #port on the application