apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template: #tell Depl which pods to manage
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: mantillabigfoot/event-bus
          imagePullPolicy: Never
--- # create new Object
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  type: ClusterIP # default
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005 #port of the k8s service
      targetPort: 4005  #port on the application