apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template: #tell Depl which pods to manage
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: mantillabigfoot/moderation
          imagePullPolicy: Never
--- # create new Object
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  type: ClusterIP # default
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003 #port of the k8s service
      targetPort: 4003  #port on the application